name: Deploy Live Editor
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build & Deploy
        run: |
          npm i -g yarn
          yarn install
          yarn release
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./docs/*
          git commit -m "Release"
          git push
